// frontend-nextjs/components/NavbarLink.tsx
import Link from "next/link";

interface NavbarLinkProps {
  href: string;
  name: string;
}

export default function NavbarLink({href, name}: NavbarLinkProps) {
  return(
    <div className="text-black dark:text-white hover:text-blue-400">
      <Link href={href}>
        {name}
      </Link>
    </div>
  )
}

// frontend/src/components/NavbarLink.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router';
defineProps({
    to: {
        type: String,
        required: true,
    },
})
</script>

<template>
    <RouterLink :to=$props.to class="text-black dark:text-white hover:text-blue-400">
        <slot></slot>
    </RouterLink>
</template>
